let recognition=null,listening=false,lastTranslation="";const langMap={en:"en-US",hi:"hi-IN",bn:"bn-IN",or:"or-IN",ta:"ta-IN",te:"te-IN",mr:"mr-IN"};
function showToast(m){const t=document.getElementById("toast");t.textContent=m;t.style.display="block";setTimeout(()=>t.style.display="none",2500)}
function toggleListening(){listening?stopListening():startVoice()}
function startVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){showToast("Speech recognition is best supported in Chrome");return}recognition=new SR();recognition.lang=langMap[document.getElementById("sourceLanguage").value]||"en-IN";recognition.continuous=true;recognition.interimResults=true;recognition.onresult=e=>{let final="",interim="";for(let i=e.resultIndex;i<e.results.length;i++){e.results[i].isFinal?final+=e.results[i][0].transcript+" ":interim+=e.results[i][0].transcript}if(final)document.getElementById("inputText").value+=(document.getElementById("inputText").value?" ":"")+final;document.getElementById("micStatus").textContent=interim?"● HEARING: "+interim:"● LISTENING"};recognition.onend=()=>{if(listening)recognition.start()};recognition.onerror=()=>showToast("Microphone error. Check permission.");recognition.start();listening=true;document.body.classList.add("listening");document.getElementById("startBtn").textContent="⏹ Stop Listening";document.getElementById("micStatus").textContent="● LISTENING LIVE"}
function stopListening(){listening=false;if(recognition)recognition.stop();document.body.classList.remove("listening");document.getElementById("startBtn").textContent="🎤 Start Listening";document.getElementById("micStatus").textContent="● READY"}
async function translateLesson(){const text=document.getElementById("inputText").value.trim(),src=document.getElementById("sourceLanguage").value,tgt=document.getElementById("targetLanguage").value,status=document.getElementById("translationStatus"),out=document.getElementById("translationResult");if(!text)return showToast("Enter or speak text first");if(src===tgt){out.textContent=text;lastTranslation=text;return}satus="";out.textContent="Translating...";status.textContent="Connecting to translation service...";try{const url="https://api.mymemory.translated.net/get?q="+encodeURIComponent(text)+"&langpair="+src+"|"+tgt;const r=await fetch(url);const d=await r.json();if(!d.responseData?.translatedText)throw Error();lastTranslation=d.responseData.translatedText;out.textContent=lastTranslation;status.textContent="✓ Translation completed. Tap Native Pronunciation to hear it.";showToast("Translation completed!")}catch(e){const fallback={hi:"यह आम है।",or:"ଏହା ଏକ ଆମ୍ବ।",bn:"এটি একটি আম।",en:text};lastTranslation=fallback[tgt]||"Translation service unavailable for this language. Connect a production translation API.";out.textContent=lastTranslation;status.textContent="Demo fallback used. Add a production translation API for full coverage.";showToast("Showing demo fallback")}}
function speakResult(){const text=lastTranslation||document.getElementById("translationResult").innerText;if(!text||text.includes("appear"))return showToast("Translate text first");speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);const code=document.getElementById("targetLanguage").value;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang.toLowerCase().startsWith(code))||null;u.lang=langMap[code]||code;u.rate=.9;speechSynthesis.speak(u)}
speechSynthesis.onvoiceschanged=()=>speechSynthesis.getVoices();
function copyResult(){navigator.clipboard.writeText(lastTranslation||"");showToast("Copied to clipboard")}
function loadVideo(input){const f=input.files[0];if(!f)return;const v=document.getElementById("videoPreview");v.src=URL.createObjectURL(f);v.style.display="block";document.getElementById("videoMeta").textContent="Loaded: "+f.name+" • "+(f.size/1048576).toFixed(2)+" MB";showToast("Video loaded successfully")}
async function processVideo(){const file=document.getElementById("videoFile").files[0],box=document.getElementById("videoProgress");if(!file)return showToast("Upload a video first");box.innerHTML="⏳ Preparing video...";await wait(700);box.innerHTML="📝 Step 1/4: Ready for speech-to-text";await wait(700);box.innerHTML="🌐 Step 2/4: Target language selected";await wait(700);box.innerHTML="🔊 Step 3/4: Ready for neural voice synthesis";await wait(700);box.innerHTML="⚙️ Frontend workflow complete. Connect backend endpoint for actual Whisper transcription, translation, TTS and FFmpeg dubbing.";showToast("Pipeline prepared")}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function quickAsk(q){document.getElementById("question").value=q;askAI()}
function askAI(){const input=document.getElementById("question"),q=input.value.trim();if(!q)return;const chat=document.getElementById("chat");chat.insertAdjacentHTML("beforeend",'<div class="message user">'+q.replace(/[<>]/g,"")+'</div>');let a=q.toLowerCase().includes("example")?"Example: A mango tree needs sunlight, water, air and nutrients to grow.":q.toLowerCase().includes("why")?"It helps us understand the idea and connect it to real life.": "Let me explain simply: break the lesson into small ideas, understand each one, then practice with an example.";setTimeout(()=>{chat.insertAdjacentHTML("beforeend",'<div class="message bot">🤖 '+a+'</div>');chat.scrollTop=chat.scrollHeight},350);input.value=""}
let score=0,answered=0;function generateQuiz(){score=0;answered=0;const qs=[["What is the source of energy for plants?",["Sunlight","Plastic","Stone","Car"],0],["Which helps plants grow?",["Water","Phone","Toy","TV"],0],["What improves understanding?",["Learning in a familiar language","Skipping lessons","Ignoring class","No questions"],0]],c=document.getElementById("quizContainer");c.innerHTML=qs.map((x,i)=>'<div class="quiz-card"><b>Q'+(i+1)+'. '+x[0]+'</b><div class="options">'+x[1].map((o,j)=>'<button class="option" onclick="checkAnswer(this,'+j+','+x[2]+')">'+o+'</button>').join("")+'</div></div>').join("");document.getElementById("scoreBox").textContent=""}
function checkAnswer(b,s,c){const card=b.closest(".quiz-card");if(card.dataset.done)return;card.dataset.done=1;answered++;card.querySelectorAll(".option").forEach((x,i)=>{x.disabled=true;if(i===c)x.classList.add("correct")});if(s===c){score++;showToast("Correct! 🎉")}else b.classList.add("wrong");if(answered===3)document.getElementById("scoreBox").textContent="Final Score: "+score+" / 3 "+(score===3?"🏆 Excellent!":"📚 Keep learning!")}