const translations={hi:"पौधों को बढ़ने के लिए सूर्य का प्रकाश, पानी और हवा की आवश्यकता होती है।",or:"ଗଛଗୁଡ଼ିକ ବଢ଼ିବା ପାଇଁ ସୂର୍ଯ୍ୟାଲୋକ, ପାଣି ଏବଂ ବାୟୁ ଆବଶ୍ୟକ କରେ।",bn:"গাছের বেড়ে ওঠার জন্য সূর্যের আলো, পানি এবং বাতাস প্রয়োজন।",en:"Plants need sunlight, water and air to grow.",sa:"Plants need sunlight, water and air to grow. (Santali prototype translation layer)",na:"Plants need sunlight, water and air to grow. (Nagpuri prototype translation layer)"};
function toast(m){const t=document.getElementById("toast");t.textContent=m;t.style.display="block";setTimeout(()=>t.style.display="none",2200)}
function translateLesson(){const l=document.getElementById("targetLanguage").value,i=document.getElementById("inputText").value.trim(),r=document.getElementById("translationResult");if(!i)return toast("Please enter a lesson first");r.textContent="✨ AI is processing your lesson...";setTimeout(()=>{r.textContent=translations[l]||i;toast("Translation completed!")},650)}
function speak(t){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.rate=.9;speechSynthesis.speak(u)}
function speakResult(){const t=document.getElementById("translationResult").innerText;if(t.includes("will appear"))return toast("Translate a lesson first");speak(t)}
function copyResult(){navigator.clipboard.writeText(document.getElementById("translationResult").innerText);toast("Copied!")}
function startVoice(){const S=window.SpeechRecognition||window.webkitSpeechRecognition;if(!S)return toast("Use Chrome for voice recognition");const r=new S();r.lang="en-IN";r.start();toast("Listening...");r.onresult=e=>{document.getElementById("inputText").value=e.results[0][0].transcript;toast("Voice captured!")};r.onerror=()=>toast("Try voice input again")}
function quickAsk(q){document.getElementById("question").value=q;askAI()}
function askAI(){const input=document.getElementById("question"),q=input.value.trim();if(!q)return toast("Ask a question first");const chat=document.getElementById("chat");chat.insertAdjacentHTML("beforeend",'<div class="message user">'+q+'</div>');const l=q.toLowerCase();let a=l.includes("sunlight")?"☀️ Plants use sunlight as energy to make their own food. Think of sunlight as a plant's energy charger!":l.includes("what do plants need")?"🌱 Plants need sunlight, water, air and nutrients from soil to grow healthy.":l.includes("photosynthesis")?"🧪 Photosynthesis is how green plants use sunlight, water and air to make food.":"🤖 Great question! Bhasha AI explains lessons using simple child-friendly language. The production version can connect to an education AI model.";setTimeout(()=>{chat.insertAdjacentHTML("beforeend",'<div class="message bot">'+a+'</div>');chat.scrollTop=chat.scrollHeight;speak(a)},400);input.value=""}
let score=0,answered=0;
function generateQuiz(){score=0;answered=0;document.getElementById("scoreBox").textContent="";const qs=[["What is the main source of energy for plants?",["Sunlight","Plastic","Stone","Television"],0],["Which is needed by plants to grow?",["Water","Mobile phone","Toy","Car"],0],["What helps children understand lessons better?",["Learning in a familiar language","Skipping lessons","Ignoring teachers","Never asking questions"],0]],c=document.getElementById("quizContainer");c.innerHTML=qs.map((x,i)=>'<div class="quiz-card"><b>Q'+(i+1)+'. '+x[0]+'</b><div class="options">'+x[1].map((o,j)=>'<button class="option" onclick="checkAnswer(this,'+j+','+x[2]+')">'+o+'</button>').join("")+'</div></div>').join("");toast("AI quiz generated!")}
function checkAnswer(b,s,c){const card=b.closest(".quiz-card");if(card.dataset.done)return;card.dataset.done=1;answered++;card.querySelectorAll(".option").forEach((x,i)=>{x.disabled=true;if(i===c)x.classList.add("correct")});if(s===c){score++;toast("🎉 Correct!")}else{b.classList.add("wrong");toast("Keep learning!")};if(answered===3)document.getElementById("scoreBox").textContent="Final Score: "+score+" / 3 "+(score===3?"🏆 Excellent!":"📚 Keep Learning!")}